export const SITE_INFO = {
  name: 'P. C. Chandra Jewellers',
  tagline: 'A jewel of jewels',
  since: '1939',
  yearsOfTrust: '85',
  phone: '+91 33 2461 7000',
  tollFree: '1800-208-1939',
  email: 'customercare@pcchandrajewellers.com',
  goldRate: '22K Gold: ₹12,217/gm | 24K Gold: ₹13,327/gm (Live Rate)',
}

export const TOP_BAR_LINKS = [
  { label: 'Gold Rate Today', href: '#gold-rate' },
  { label: 'Find a Store', href: '#stores' },
  { label: 'Track Order', href: '#track' },
  { label: 'Contact Us', href: '#contact' },
]

export const NAV_LINKS = [
  { label: 'Gold', href: '#gold' },
  { label: 'Diamond', href: '#diamond' },
  { label: 'Polki & Jadau', href: '#polki' },
  { label: 'Bridal', href: '#bridal' },
  { label: 'Collections', href: '#collections' },
  { label: 'Gifting', href: '#gifting' },
  { label: 'Bespoke Atelier', href: '#custom' },
  { label: 'Daily Wear', href: '#dailywear' },
]

export const TRUST_STRIP = [
  {
    title: '100% BIS 916 Hallmarked',
    desc: 'Guaranteed purity with laser inscription',
  },
  {
    title: 'Certified Natural Diamonds',
    desc: 'Graded by premier gemological labs (IGI/SGL)',
  },
  {
    title: 'Free Insured Shipping',
    desc: 'Doorstep transit insurance across India',
  },
  {
    title: 'Transparent Lifetime Exchange',
    desc: 'Guaranteed buyback & upgrade value',
  },
]

export const HERO_DATA = {
  badge: 'SINCE 1939 • CELEBRATING 85 YEARS OF ARTISTRY',
  title: 'The Royal Bengal Heritage Collection',
  highlight: 'Crafted with Soul. Cherished Forever.',
  description:
    'Discover heirloom masterworks wrought by fourth-generation Bengali karigars. Pure 22KT gold, uncut polki diamonds, and luminous gemstones crafted into enduring symbols of grace.',
  image: '/images/hero_jewellery.jpg',
  primaryCta: 'Explore Masterpieces',
  secondaryCta: 'Book Atelier Consultation',
}

export const GENDER_TABS = [
  { id: 'women', label: "Women's Jewellery" },
  { id: 'men', label: "Men's Jewellery" },
  { id: 'kids', label: "Kids' Collection" },
]

export const CATEGORIES = [
  {
    id: 'rings',
    title: 'Rings',
    itemsCount: '420+ Designs',
    image: '/images/category_rings.jpg',
    href: '/collections?category=rings',
  },
  {
    id: 'earrings',
    title: 'Earrings & Jhumkas',
    itemsCount: '650+ Designs',
    image: '/images/category_earrings.jpg',
    href: '/collections?category=earrings',
  },
  {
    id: 'pendants',
    title: 'Pendants & Lokets',
    itemsCount: '310+ Designs',
    image: '/images/category_pendants.jpg',
    href: '/collections?category=necklaces',
  },
  {
    id: 'bangles',
    title: 'Bangles & Kadas',
    itemsCount: '280+ Designs',
    image: '/images/category_bangles.jpg',
    href: '/collections?category=bangles',
  },
  {
    id: 'necklaces',
    title: 'Necklaces & Chokers',
    itemsCount: '190+ Designs',
    image: '/images/hero_jewellery.jpg',
    href: '/collections?category=necklaces',
  },
]

export const BESPOKE_BANNER = {
  badge: 'BESPOKE ATELIER',
  title: 'Your Vision. Our Master Craft.',
  description:
    'Turn personal stories into heirloom jewellery. From private sketches to hand-selected gemstones, collaborate directly with master goldsmiths who have preserved Bengal’s jewellery traditions for over eight decades.',
  cta: 'Commission Your Design',
  image: '/images/custom_craft.jpg',
}

export const ALL_PRODUCTS = [
  // ==================== RINGS (9 items) ====================
  {
    id: 1,
    name: 'Swarnalata 22KT Gold Filigree Floral Ring',
    category: 'rings',
    metal: '22KT Hallmarked Gold • Natural Ruby Accents',
    price: 36400,
    originalPrice: 39800,
    rating: 4.9,
    reviews: 42,
    image: '/images/products/ring_01.jpg',
    badge: 'Bestseller',
    weight: '4.8g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 2,
    name: 'Kohinoor Brilliant Solitaire Diamond Ring',
    category: 'rings',
    metal: '18KT White Gold • 0.75ct VVS Diamond',
    price: 88500,
    originalPrice: 96000,
    rating: 5.0,
    reviews: 64,
    image: '/images/products/ring_02.jpg',
    badge: 'Certified',
    weight: '3.2g',
    goldColor: 'White Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 3,
    name: 'Rajmata Uncut Polki & Zambian Emerald Ring',
    category: 'rings',
    metal: '22KT Yellow Gold • Natural Emerald & Polki',
    price: 74200,
    originalPrice: 81500,
    rating: 4.8,
    reviews: 29,
    image: '/images/products/ring_03.jpg',
    badge: 'Heritage',
    weight: '7.1g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 10,
    videoPreview: true,
  },
  {
    id: 4,
    name: 'Manikya Halo Oval Ruby & Diamond Ring',
    category: 'rings',
    metal: '18KT Yellow Gold • Burmese Ruby • SI-IJ Diamond',
    price: 52900,
    originalPrice: 58000,
    rating: 4.9,
    reviews: 35,
    image: '/images/products/ring_04.jpg',
    badge: 'Trending',
    weight: '3.9g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 5,
    name: 'Ananya Vintage Hand-Carved Rose Gold Band',
    category: 'rings',
    metal: '18KT Rose Gold • Intricate Milgrain Art',
    price: 28900,
    originalPrice: 32000,
    rating: 4.7,
    reviews: 19,
    image: '/images/products/ring_05.jpg',
    badge: 'Daily Luxury',
    weight: '3.4g',
    goldColor: 'Rose Gold',
    gender: 'Women',
    metalPurity: '14KT Gold',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 6,
    name: "Maharaja Royal Signet Ring for Men",
    category: 'rings',
    subCategory: 'mens',
    metal: '22KT Solid Yellow Gold • Geometric Intaglio',
    price: 64800,
    originalPrice: 71000,
    rating: 5.0,
    reviews: 58,
    image: '/images/products/ring_06.jpg',
    badge: "Men's Luxury",
    weight: '8.5g',
    goldColor: 'Yellow Gold',
    gender: 'Men',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 7,
    name: 'Navratna Nine-Gem Sacred Gold Ring',
    category: 'rings',
    metal: '22KT BIS 916 Gold • Certified 9 Precious Gems',
    price: 49500,
    originalPrice: 54000,
    rating: 4.9,
    reviews: 47,
    image: '/images/products/ring_07.jpg',
    badge: 'Auspicious',
    weight: '5.6g',
    goldColor: 'Yellow Gold',
    gender: 'Unisex',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 8,
    name: 'Nakshi Carved Feather Art 22KT Ring',
    category: 'rings',
    metal: '22KT Yellow Gold • Antique Matte Finish',
    price: 43200,
    originalPrice: 47500,
    rating: 4.8,
    reviews: 31,
    image: '/images/products/ring_08.jpg',
    badge: 'Artisanal',
    weight: '5.8g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 10,
    videoPreview: true,
  },
  {
    id: 9,
    name: 'Eternal Round Brilliant Diamond Eternity Band',
    category: 'rings',
    metal: '18KT Platinum & White Gold • 1.20ct Diamonds',
    price: 94000,
    originalPrice: 104000,
    rating: 5.0,
    reviews: 53,
    image: '/images/products/ring_09.jpg',
    badge: 'Bestseller',
    weight: '4.1g',
    goldColor: 'White Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },

  // ==================== EARRINGS & JHUMKAS (9 items) ====================
  {
    id: 10,
    name: 'Mayurpankhi 22KT Gold Filigree Jhumkas',
    category: 'earrings',
    metal: '22KT Yellow Gold • Basra Seed Pearls',
    price: 86500,
    originalPrice: 94000,
    rating: 5.0,
    reviews: 78,
    image: '/images/products/earring_01.jpg',
    badge: 'Bengali Iconic',
    weight: '11.4g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 11,
    name: 'Starlight Cascading Diamond Chandelier Drops',
    category: 'earrings',
    metal: '18KT White Gold • 1.85ct Certified Diamonds',
    price: 135000,
    originalPrice: 148000,
    rating: 4.9,
    reviews: 41,
    image: '/images/products/earring_02.jpg',
    badge: 'Red Carpet',
    weight: '8.2g',
    goldColor: 'White Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 12,
    name: 'Begum Hazrat Polki & Seed Pearl Chandbalis',
    category: 'earrings',
    metal: '22KT Gold • Uncut Polki Diamonds • Micro Pearls',
    price: 112000,
    originalPrice: 122000,
    rating: 5.0,
    reviews: 36,
    image: '/images/products/earring_03.jpg',
    badge: 'Bridal Royal',
    weight: '14.6g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 10,
    videoPreview: true,
  },
  {
    id: 13,
    name: 'Gulmohar Burma Ruby & Diamond Cluster Studs',
    category: 'earrings',
    metal: '18KT Yellow Gold • Natural Ruby • Floral Pavé',
    price: 58000,
    originalPrice: 63500,
    rating: 4.8,
    reviews: 28,
    image: '/images/products/earring_04.jpg',
    badge: 'Trending',
    weight: '4.5g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 14,
    name: 'Panna Royal Zambian Emerald Teardrop Danglers',
    category: 'earrings',
    metal: '18KT Yellow Gold • Pear Cut Emeralds • Halo Diamonds',
    price: 98000,
    originalPrice: 108000,
    rating: 5.0,
    reviews: 49,
    image: '/images/products/earring_05.jpg',
    badge: 'High Jewellery',
    weight: '7.8g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 15,
    name: 'Nakshi Dancing Peacock 22KT Gold Earrings',
    category: 'earrings',
    metal: '22KT Hallmarked Gold • Pearl Drops • Nakshi Karigari',
    price: 69400,
    originalPrice: 76000,
    rating: 4.9,
    reviews: 62,
    image: '/images/products/earring_06.jpg',
    badge: 'Heritage Classic',
    weight: '9.3g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 16,
    name: 'Solitaire Round Diamond Solitaire Studs',
    category: 'earrings',
    metal: '18KT White Gold • 0.90ct TW VVS-EF Diamonds',
    price: 79900,
    originalPrice: 87000,
    rating: 5.0,
    reviews: 83,
    image: '/images/products/earring_07.jpg',
    badge: 'Timeless Essential',
    weight: '2.6g',
    goldColor: 'White Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 17,
    name: 'Tradition Kanpasha 22KT Gold Ear-Studs',
    category: 'earrings',
    metal: '22KT Pure Gold • Ruby & Basra Pearl Accents',
    price: 54200,
    originalPrice: 59500,
    rating: 4.9,
    reviews: 44,
    image: '/images/products/earring_08.jpg',
    badge: 'Bengali Tradition',
    weight: '7.2g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 18,
    name: 'Avant-Garde Rose Gold Geometric Diamond Drops',
    category: 'earrings',
    metal: '18KT Rose Gold • Micro Pavé Diamonds',
    price: 46800,
    originalPrice: 51200,
    rating: 4.8,
    reviews: 27,
    image: '/images/products/earring_09.jpg',
    badge: 'Modern Chic',
    weight: '4.8g',
    goldColor: 'Rose Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },

  // ==================== NECKLACES & PENDANTS (9 items) ====================
  {
    id: 19,
    name: 'Rajwada Filigree Hansuli Bridal Gold Choker',
    category: 'necklaces',
    metal: '22KT BIS 916 Yellow Gold • Handwoven Pearls',
    price: 185000,
    originalPrice: 202000,
    rating: 5.0,
    reviews: 67,
    image: '/images/products/necklace_01.jpg',
    badge: 'Bridal Heirloom',
    weight: '26.5g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 20,
    name: 'Mayur Nakshi Antique Gold Peacock Pendant',
    category: 'necklaces',
    metal: '22KT Gold • Emerald & Ruby Cabochons • Thick Chain',
    price: 92400,
    originalPrice: 101000,
    rating: 4.9,
    reviews: 53,
    image: '/images/products/necklace_02.jpg',
    badge: 'Masterpiece',
    weight: '14.2g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 21,
    name: 'Celestial Solitaire Floating Diamond Pendant',
    category: 'necklaces',
    metal: '18KT White Gold • 0.80ct Solitaire • Platinum Link',
    price: 76000,
    originalPrice: 83500,
    rating: 4.9,
    reviews: 38,
    image: '/images/products/necklace_03.jpg',
    badge: 'Everyday Brilliance',
    weight: '3.1g',
    goldColor: 'White Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 22,
    name: 'Nizam Emerald & Jadau Polki Royal Bridal Haar',
    category: 'necklaces',
    metal: '22KT Gold • Colombian Emerald Drops • Uncut Polki',
    price: 245000,
    originalPrice: 268000,
    rating: 5.0,
    reviews: 31,
    image: '/images/products/necklace_04.jpg',
    badge: 'Royalty Edition',
    weight: '34.8g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 10,
    videoPreview: true,
  },
  {
    id: 23,
    name: 'Kasu Mala Divine Lakshmi 22KT Coin Necklace',
    category: 'necklaces',
    metal: '22KT Pure Gold • Hand-Struck Lakshmi Coins',
    price: 158000,
    originalPrice: 172000,
    rating: 5.0,
    reviews: 89,
    image: '/images/products/necklace_05.jpg',
    badge: 'Sacred Heritage',
    weight: '24.0g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 24,
    name: 'Gulshan Starburst Ruby & Diamond Pendant',
    category: 'necklaces',
    metal: '18KT White Gold • Pigeon Blood Ruby • Brilliant Diamonds',
    price: 68500,
    originalPrice: 75000,
    rating: 4.8,
    reviews: 26,
    image: '/images/products/necklace_06.jpg',
    badge: 'Festive Special',
    weight: '5.4g',
    goldColor: 'White Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 25,
    name: 'Tarangini Dual-Layer Gold & South Sea Pearl Mala',
    category: 'necklaces',
    metal: '22KT Yellow Gold • Natural Luster Pearls',
    price: 84000,
    originalPrice: 91500,
    rating: 4.9,
    reviews: 43,
    image: '/images/products/necklace_07.jpg',
    badge: 'Contemporary Classic',
    weight: '12.8g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 26,
    name: 'Shrimati Solitaire Diamond Traditional Mangalsutra',
    category: 'necklaces',
    metal: '18KT Yellow Gold • Black Onyx Beads • Certified Diamond',
    price: 62000,
    originalPrice: 68000,
    rating: 5.0,
    reviews: 95,
    image: '/images/products/necklace_08.jpg',
    badge: 'Sacred Bond',
    weight: '6.5g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 27,
    name: 'Brihadisvara Temple Antique Nakshi Gold Choker',
    category: 'necklaces',
    metal: '22KT Antique Finish Gold • Rubies & Emerald Drops',
    price: 215000,
    originalPrice: 236000,
    rating: 5.0,
    reviews: 57,
    image: '/images/products/necklace_09.jpg',
    badge: 'Museum Edition',
    weight: '31.2g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 10,
    videoPreview: true,
  },

  // ==================== BANGLES & KADAS (9 items) ====================
  {
    id: 28,
    name: 'Mayur Mukhi Royal 22KT Gold Peacock Kada (Pair)',
    category: 'bangles',
    metal: '22KT Yellow Gold • Ruby Eyes • Nakshi Feather Art',
    price: 198000,
    originalPrice: 215000,
    rating: 5.0,
    reviews: 74,
    image: '/images/products/bangle_01.jpg',
    badge: 'Heritage Showpiece',
    weight: '28.4g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 29,
    name: 'Koh-i-Noor Classic Diamond Tennis Bracelet',
    category: 'bangles',
    metal: '18KT White Gold • 2.50ct TW Brilliant Diamonds',
    price: 165000,
    originalPrice: 180000,
    rating: 5.0,
    reviews: 48,
    image: '/images/products/bangle_02.jpg',
    badge: 'Luxury Diamond',
    weight: '9.6g',
    goldColor: 'White Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 30,
    name: 'Nilambari Polki & Cabochon Emerald Royal Kada',
    category: 'bangles',
    metal: '22KT Yellow Gold • Uncut Polki Diamonds • Zambian Emeralds',
    price: 142000,
    originalPrice: 156000,
    rating: 4.9,
    reviews: 33,
    image: '/images/products/bangle_03.jpg',
    badge: 'Royal Vintage',
    weight: '19.8g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 10,
    videoPreview: true,
  },
  {
    id: 31,
    name: 'Chandrakala Antique Floral Carved Bala Pair',
    category: 'bangles',
    metal: '22KT Hallmarked Gold • Traditional Bengali Nakshi',
    price: 128000,
    originalPrice: 139000,
    rating: 4.9,
    reviews: 82,
    image: '/images/products/bangle_04.jpg',
    badge: 'Bestseller',
    weight: '18.2g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 32,
    name: 'Zephyr Dual-Bar Diamond Open Cuff Bracelet',
    category: 'bangles',
    metal: '18KT White Gold • Channel Set Diamonds',
    price: 88000,
    originalPrice: 96000,
    rating: 4.8,
    reviews: 29,
    image: '/images/products/bangle_05.jpg',
    badge: 'Modern Luxury',
    weight: '8.4g',
    goldColor: 'White Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 33,
    name: 'Ashta Lakshmi Divine Temple Carved Gold Kada',
    category: 'bangles',
    metal: '22KT Antique Gold • High Relief Sacred Karigari',
    price: 175000,
    originalPrice: 192000,
    rating: 5.0,
    reviews: 61,
    image: '/images/products/bangle_06.jpg',
    badge: 'Divine Heritage',
    weight: '25.6g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 10,
    videoPreview: true,
  },
  {
    id: 34,
    name: 'Aashna Elephant & Lotus Diamond Charm Bracelet',
    category: 'bangles',
    metal: '18KT Rose Gold • Micro Pavé Diamond Charms',
    price: 59000,
    originalPrice: 65000,
    rating: 4.9,
    reviews: 39,
    image: '/images/products/bangle_07.jpg',
    badge: 'Playful Elegance',
    weight: '6.8g',
    goldColor: 'Rose Gold',
    gender: 'Kids',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 35,
    name: 'Jaali Bengali Hand-Filigree 22KT Gold Bangle Pair',
    category: 'bangles',
    metal: '22KT Pure Gold • Century-Old Bowbazar Lattice Art',
    price: 148000,
    originalPrice: 162000,
    rating: 5.0,
    reviews: 73,
    image: '/images/products/bangle_08.jpg',
    badge: 'Karigari Special',
    weight: '21.0g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 36,
    name: "Samrat Satin Finish Solid 22KT Gold Kada for Men",
    category: 'bangles',
    subCategory: 'mens',
    metal: '22KT Solid Gold • Brushed Satin Finish • Hinge Lock',
    price: 122000,
    originalPrice: 134000,
    rating: 4.9,
    reviews: 55,
    image: '/images/products/bangle_09.jpg',
    badge: "Men's Heritage",
    weight: '18.5g',
    goldColor: 'Yellow Gold',
    gender: 'Men',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },

  // ==================== BRIDAL & TEMPLE HEIRLOOM (9 items) ====================
  {
    id: 37,
    name: 'Rajkanya 22KT Gold Filigree Bridal Choker',
    category: 'bridal',
    metal: '22KT BIS 916 Gold • Cluster Basra Pearls • Ruby Center',
    price: 235000,
    originalPrice: 255000,
    rating: 5.0,
    reviews: 88,
    image: '/images/products/bridal_01.jpg',
    badge: 'Bridal Grandeur',
    weight: '36.5g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 38,
    name: 'Chandni Polki & Pearl Bridal Matha Patti',
    category: 'bridal',
    metal: '22KT Gold • Hand-Set Uncut Polki Diamonds • Basra Pearls',
    price: 148000,
    originalPrice: 162000,
    rating: 4.9,
    reviews: 46,
    image: '/images/products/bridal_02.jpg',
    badge: 'Royal Heirloom',
    weight: '22.0g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 10,
    videoPreview: true,
  },
  {
    id: 39,
    name: 'Arundhati Handcrafted Pearl & Gold Bridal Nath',
    category: 'bridal',
    metal: '22KT Yellow Gold • Natural Pearls & Ruby • Delicate Chain',
    price: 42000,
    originalPrice: 46500,
    rating: 4.8,
    reviews: 33,
    image: '/images/products/bridal_03.jpg',
    badge: 'Traditional',
    weight: '6.2g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 40,
    name: 'Padmavati Imperial Polki Hathphool (5-Ring Harness)',
    category: 'bridal',
    metal: '22KT Gold • Jadau Polki Setting • Adjustable Rings',
    price: 175000,
    originalPrice: 192000,
    rating: 5.0,
    reviews: 39,
    image: '/images/products/bridal_04.jpg',
    badge: 'High Jewellery',
    weight: '28.4g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 10,
    videoPreview: true,
  },
  {
    id: 41,
    name: 'Mahalakshmi Antique Temple Gold Kamarbandh Belt',
    category: 'bridal',
    metal: '22KT Antique Nakshi Gold • Carved Deities • Emerald Drops',
    price: 345000,
    originalPrice: 380000,
    rating: 5.0,
    reviews: 29,
    image: '/images/products/bridal_05.jpg',
    badge: 'Temple Art',
    weight: '54.0g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 25,
    videoPreview: true,
  },
  {
    id: 42,
    name: 'Rani Sahiba Ruby Drop Bridal Chand Jhumkas',
    category: 'bridal',
    metal: '22KT Yellow Gold • Pigeon Blood Rubies • Double Tier Jhumka',
    price: 98000,
    originalPrice: 108000,
    rating: 4.9,
    reviews: 62,
    image: '/images/products/bridal_06.jpg',
    badge: 'Bestseller',
    weight: '15.8g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 43,
    name: 'Sampriti Geometric Solitaire Diamond Mangalsutra',
    category: 'bridal',
    metal: '18KT White & Yellow Gold • VVS Diamonds • Auspicious Onyx',
    price: 68000,
    originalPrice: 74500,
    rating: 5.0,
    reviews: 94,
    image: '/images/products/bridal_07.jpg',
    badge: 'Sacred Vows',
    weight: '5.8g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 44,
    name: 'Mayur Emerald & Polki Royal Armlet (Bajuband)',
    category: 'bridal',
    metal: '22KT Gold • Zambian Cabochon Emeralds • Basra Pearl Fringe',
    price: 165000,
    originalPrice: 180000,
    rating: 4.9,
    reviews: 24,
    image: '/images/products/bridal_08.jpg',
    badge: 'Artisanal',
    weight: '24.6g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 10,
    videoPreview: true,
  },
  {
    id: 45,
    name: 'Raj-Darbar Three-Tier Temple Gold Sita Haar',
    category: 'bridal',
    metal: '22KT Antique Gold • Hand-Chiseled Temple Medallions',
    price: 420000,
    originalPrice: 460000,
    rating: 5.0,
    reviews: 51,
    image: '/images/products/bridal_09.jpg',
    badge: 'Imperial Masterpiece',
    weight: '68.2g',
    goldColor: 'Yellow Gold',
    gender: 'Women',
    metalPurity: '22KT Gold',
    deliveryDays: 25,
    videoPreview: true,
  },

  // ==================== MEN'S & FINE MODERN DIAMOND (9 items) ====================
  {
    id: 46,
    name: 'Vikramaditya Heavy 22KT Gold Cuban Chain for Men',
    category: 'mens',
    metal: '22KT Solid Gold • Diamond-Cut Cuban Links • Lobster Lock',
    price: 215000,
    originalPrice: 235000,
    rating: 5.0,
    reviews: 81,
    image: '/images/products/mens_01.jpg',
    badge: "Men's Statement",
    weight: '32.0g',
    goldColor: 'Yellow Gold',
    gender: 'Men',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 47,
    name: 'Regal Onyx & Certified Diamond Gold Cufflinks',
    category: 'mens',
    metal: '18KT Yellow Gold • Jet Black Onyx • Pavé Diamonds',
    price: 78000,
    originalPrice: 86000,
    rating: 4.9,
    reviews: 37,
    image: '/images/products/mens_02.jpg',
    badge: 'Black Tie',
    weight: '10.5g',
    goldColor: 'Yellow Gold',
    gender: 'Men',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 48,
    name: 'Maharawal Natural Emerald Signet Ring in 22KT Gold',
    category: 'mens',
    metal: '22KT Solid Gold • 3.5ct Natural Emerald Cabochon',
    price: 89000,
    originalPrice: 97000,
    rating: 4.9,
    reviews: 49,
    image: '/images/products/mens_03.jpg',
    badge: 'Royal Sovereign',
    weight: '12.8g',
    goldColor: 'Yellow Gold',
    gender: 'Men',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 49,
    name: 'Orion Solitaire Floating Diamond Pendant in White Gold',
    category: 'necklaces',
    metal: '18KT White Gold • 0.95ct Solitaire Diamond • Platinum Chain',
    price: 92000,
    originalPrice: 101000,
    rating: 5.0,
    reviews: 58,
    image: '/images/products/mens_04.jpg',
    badge: 'Certified VVS',
    weight: '3.8g',
    goldColor: 'White Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 50,
    name: 'Anantya Infinity Diamond Pavé Rose Gold Charm Bracelet',
    category: 'bangles',
    metal: '18KT Rose Gold • Infinity Motif • Certified Natural Diamonds',
    price: 62000,
    originalPrice: 68500,
    rating: 4.8,
    reviews: 41,
    image: '/images/products/mens_05.jpg',
    badge: 'Modern Chic',
    weight: '6.2g',
    goldColor: 'Rose Gold',
    gender: 'Women',
    metalPurity: '18KT Diamond',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 51,
    name: 'Singhasan Sculpted Lion Head Solid 22KT Gold Kada',
    category: 'mens',
    metal: '22KT Heavy Solid Gold • Hand-Sculpted Lion Head • Ruby Eyes',
    price: 265000,
    originalPrice: 290000,
    rating: 5.0,
    reviews: 63,
    image: '/images/products/mens_06.jpg',
    badge: 'Imperial Emblem',
    weight: '42.0g',
    goldColor: 'Yellow Gold',
    gender: 'Men',
    metalPurity: '22KT Gold',
    deliveryDays: 7,
    videoPreview: true,
  },
  {
    id: 52,
    name: 'Koh-i-Noor Starburst Multi-Cut Diamond Brooch Pin',
    category: 'rings',
    metal: '18KT White Gold • Marquise & Brilliant Cut Diamonds',
    price: 185000,
    originalPrice: 205000,
    rating: 5.0,
    reviews: 28,
    image: '/images/products/mens_07.jpg',
    badge: 'Couture Fine',
    weight: '14.2g',
    goldColor: 'White Gold',
    gender: 'Unisex',
    metalPurity: '18KT Diamond',
    deliveryDays: 10,
    videoPreview: true,
  },
  {
    id: 53,
    name: 'Aethelgard Two-Tone Gold & Platinum Diamond Band',
    category: 'rings',
    metal: '950 Platinum & 18KT Yellow Gold • Channel Diamonds',
    price: 74000,
    originalPrice: 81000,
    rating: 4.9,
    reviews: 52,
    image: '/images/products/mens_08.jpg',
    badge: 'Platinum Guild',
    weight: '7.8g',
    goldColor: 'White Gold',
    gender: 'Men',
    metalPurity: 'Platinum',
    deliveryDays: 3,
    videoPreview: true,
  },
  {
    id: 54,
    name: 'Siddhi Vinayak Lord Ganesha Diamond Pendant with Chain',
    category: 'necklaces',
    metal: '22KT Gold • Natural Rubies • Certified Diamond Crown',
    price: 105000,
    originalPrice: 115000,
    rating: 5.0,
    reviews: 112,
    image: '/images/products/mens_09.jpg',
    badge: 'Sacred Auspicious',
    weight: '16.5g',
    goldColor: 'Yellow Gold',
    gender: 'Unisex',
    metalPurity: '22KT Gold',
    deliveryDays: 3,
    videoPreview: true,
  },
]

// Curated 4 display masterpieces for Homepage Showcase
export const FEATURED_PRODUCTS = [
  ALL_PRODUCTS[0],  // Swarnalata Ring
  ALL_PRODUCTS[9],  // Mayurpankhi Jhumkas
  ALL_PRODUCTS[18], // Rajwada Filigree Choker
  ALL_PRODUCTS[27], // Mayur Mukhi Peacock Kada
]

export const LIVE_CONSULTATION = {
  badge: 'CONCIERGE SERVICE',
  title: 'Shop Latest Collections Live on Video Call',
  description:
    'Experience the warmth and intimacy of our flagship showrooms from the comfort of your home. Our certified gemologists present every piece in 360-degree clarity, answer styling queries, and help you select the perfect piece.',
  cta: 'Schedule Video Appointment',
  image: '/images/live_consultation.jpg',
}

export const GIFTING_COLLECTIONS = [
  {
    title: 'Bridal & Wedding',
    tagline: 'Regal sets for life’s most auspicious milestone',
    image: '/images/gifting_wedding.jpg',
    href: '/collections?category=bridal',
  },
  {
    title: 'Anniversary Solitaires',
    tagline: 'Timeless diamonds to celebrate enduring love',
    image: '/images/gifting_anniversary.jpg',
    href: '/collections?metal=diamond',
  },
  {
    title: 'Distinguished For Him',
    tagline: 'Understated gold signets, kadas & chains',
    image: '/images/gifting_for_him.jpg',
    href: '/collections?category=mens&gender=men',
  },
  {
    title: 'Personalized Creations',
    tagline: 'Custom initials, zodiacs & tailored charms',
    image: '/images/gifting_personalized.jpg',
    href: '/collections?category=rings',
  },
]

export const PRICE_TIERS = [
  { label: 'Gifts Under', price: '₹25,000', href: '/collections?maxPrice=25000' },
  { label: 'Gifts Under', price: '₹50,000', href: '/collections?maxPrice=50000' },
  { label: 'Gifts Under', price: '₹75,000', href: '/collections?maxPrice=75000' },
  { label: 'Luxury Above', price: '₹1,00,000', href: '/collections?minPrice=100000' },
]

export const HERITAGE_STORY = {
  since: '1939',
  title: 'The Legacy of P. C. Chandra Jewellers',
  paragraphs: [
    'Founded in 1939 by Shri Purna Chandra Chandra in Bowbazar, the historic jewellery quarter of Kolkata, P. C. Chandra Jewellers has been an indomitable beacon of trust, purity, and exquisite Bengali craftsmanship for over 85 years.',
    'Over four generations, our family has nurtured the intricate arts of filigree, nakshi, and jadau. Each creation is not merely an ornament, but an enduring heirloom infused with Bengal’s artistic soul and certified for supreme purity.',
  ],
  stats: [
    { value: '85+', label: 'Years of Heritage' },
    { value: '70+', label: 'Boutiques Across India' },
    { value: '10M+', label: 'Families Cherished' },
    { value: '100%', label: 'Hallmarked Purity' },
  ],
  image: '/images/heritage_showroom.jpg',
  cta: 'Explore Our Heritage Story',
}

export const TESTIMONIALS = [
  {
    quote:
      'We bought our daughter’s bridal necklace from P.C. Chandra, just as my father bought mine in 1988. The craftsmanship is divine and the transparency in pricing has remained unchanged across generations.',
    author: 'Suniti & Debashis Ganguly',
    location: 'Kolkata, West Bengal',
    occasion: 'Bridal Set Purchase',
    verified: true,
  },
  {
    quote:
      'The video consultation was seamless. The jewellery specialist patiently showed me three different diamond rings under varied lights. The ring arrived in sealed tamper-proof packaging with full IGI certification.',
    author: 'Ananya Mukherjee',
    location: 'Bengaluru, Karnataka',
    occasion: 'Anniversary Solitaire',
    verified: true,
  },
  {
    quote:
      'Authentic Bengali filigree work is nearly impossible to find outside Kolkata. Ordering online gave me the same confidence as visiting the Bowbazar showroom.',
    author: 'Dr. Rituparna Roy',
    location: 'New Delhi',
    occasion: 'Gold Filigree Jhumkas',
    verified: true,
  },
]

export const TRUST_TOKENS = [
  {
    id: 1,
    title: '100% BIS Hallmarked',
    desc: 'Government certified 916 gold purity with tamper-proof laser inscription.',
  },
  {
    id: 2,
    title: 'Certified Natural Diamonds',
    desc: 'Graded by independent international laboratories (IGI, SGL).',
  },
  {
    id: 3,
    title: 'Transparent Pricing',
    desc: 'Itemized breakdown of gold weight, stone weight, and making charges.',
  },
  {
    id: 4,
    title: 'Accurate Karatmeter Testing',
    desc: 'Complimentary computerized purity verification at all showrooms.',
  },
  {
    id: 5,
    title: 'Guaranteed Buyback & Exchange',
    desc: 'Best exchange value on gold and diamond jewellery across all boutiques.',
  },
  {
    id: 6,
    title: 'Free Insured Doorstep Delivery',
    desc: '100% transit insurance with sealed high-security tamper packaging.',
  },
  {
    id: 7,
    title: '14-Day Hassle-Free Returns',
    desc: 'Unhindered refund or exchange policy if you are not delighted.',
  },
  {
    id: 8,
    title: 'Master Bengali Karigari',
    desc: 'Preserving century-old handmade nakshi and filigree techniques.',
  },
  {
    id: 9,
    title: 'Lifetime Maintenance & Cleaning',
    desc: 'Complimentary ultrasonic polish and setting inspection for life.',
  },
  {
    id: 10,
    title: '85 Years of Pure Trust',
    desc: 'Serving Indian families with honesty and devotion since 1939.',
  },
]

export const FOOTER_SECTIONS = {
  brandStory: {
    title: 'THE BRAND STORY',
    links: [
      { label: 'P.C. Chandra Jewellers', href: '#brand' },
      { label: 'CSR Activities', href: '#csr' },
      { label: 'Get In Touch', href: '#contact' },
      { label: 'Career', href: '#career' },
      { label: 'Blogs', href: '#blogs' },
    ],
  },
  brandProperties: {
    title: 'BRAND PROPERTIES',
    links: [{ label: 'P.C. Chandra Puraskaar', href: '#puraskaar' }],
  },
  contact: {
    title: 'CONTACT US',
    email: 'customercare@pcchandraindia.com',
    phone: '+91 8010700400 (10:00am to 6:30pm)',
  },
  collections: {
    title: 'OUR COLLECTIONS',
    links: [
      { label: 'Wedding', href: '/collections?category=bridal' },
      { label: 'Diamond', href: '/collections?metal=diamond' },
      { label: 'Goldlites', href: '/collections?metal=gold' },
      { label: 'Amazea', href: '/collections' },
      { label: 'Kids', href: '/collections?gender=kids' },
      { label: 'Mugdhaa', href: '/collections?category=rings' },
    ],
  },
  media: {
    title: 'MEDIA & ADVERTISEMENT',
    links: [
      { label: 'Print Media', href: '#print' },
      { label: 'TV Commercials', href: '#tv' },
      { label: 'Photo Gallery', href: '#gallery' },
      { label: 'Video Gallery', href: '#videos' },
      { label: 'Press Room', href: '#press' },
    ],
  },
  categories: {
    title: 'OUR CATEGORIES',
    links: [
      { label: 'Gold', href: '/collections?metal=gold' },
      { label: 'Diamond', href: '/collections?metal=diamond' },
      { label: 'Silver & Platinum', href: '/collections?metal=platinum' },
      { label: 'GEMSTONE', href: '/collections?category=rings' },
    ],
  },
  social: {
    title: 'FOLLOW US',
    links: [
      { label: 'Facebook', href: 'https://facebook.com' },
      { label: 'X', href: 'https://x.com' },
      { label: 'Instagram', href: 'https://instagram.com' },
      { label: 'Youtube', href: 'https://youtube.com' },
      { label: 'WhatsApp', href: 'https://whatsapp.com' },
    ],
  },
  newsletter: {
    title: 'JOIN OUR NEWSLETTER',
    subtitle: 'For Our Latest Updates & Promotions',
  },
  legalLinks: [
    { label: 'Privacy Policy', href: '#privacy' },
    { label: 'Shipping Policy', href: '#shipping' },
    { label: 'Dispute Resolution Policy', href: '#dispute' },
    { label: 'Terms & Conditions', href: '#terms' },
    { label: 'Cancellation, Return and Refund Policy', href: '#refund' },
    { label: 'Buyback & Exchange policy', href: '#exchange' },
    { label: 'Terms and Conditions (P.C. Chandra Jewellers)', href: '#pcc-terms' },
    { label: 'FAQ', href: '#faq' },
  ],
  copyright: '© 2026 P.C. CHANDRA (GEMS) PRIVATE LIMITED. ALL RIGHTS RESERVED',
}
